# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
  branches:
    include:
      - '*'
  paths:
    exclude:
      - README.md
      - azure-pipelines.yml
pr:
  branches:
    include:
      - main
  paths:
    exclude:
      - README.md
      - .gitignore
      - LICENSE

variables:
- name: applyBranch
  value:  $[eq(variables['Build.SourceBranch'], 'refs/heads/main')]
- name: tfWorkingDir
  value:  infra
- name: ansibleWorkingDir
  value: ansible
- name: terraformVersion
  value: 1.3.9


parameters:
- name: serviceConnectionName
  default: 'Azure subscription 1 (96a83b50-c77d-40ae-b8b9-4930e9787e23)'
- name: environment
  default: prod
- name: terraformVersion
  default: 1.3.9
- name: tfWorkingDirectory
  default: infra

pool:
  vmImage: ubuntu-latest

stages:
#- stage: update_shared_values
#  displayName: "Update required variable values"
#  jobs:
#    - job: update_conf
#      displayName: "Update conf toml"
#      steps:
        
#    - job: update_db
#      displayName: "Update db details"
# This is something to be done later, replacing the terraform dbname and conf.toml. and referring library variable groups in azure devops. Would make things a lot managable.

- stage: tf_plan
  displayName: "Terraform plan"
  jobs:
    - job: plan

      steps:
        - task: charleszipp.azure-pipelines-tasks-terraform.azure-pipelines-tasks-terraform-installer.TerraformInstaller@0
          displayName: "Use Terraform latest"
          inputs:
            terraformVersion: "${{ parameters.terraformVersion }}"

        - task: charleszipp.azure-pipelines-tasks-terraform.azure-pipelines-tasks-terraform-cli.TerraformCLI@0
          displayName: "Terraform format"
          inputs:
            command: fmt
            workingDirectory: "$(System.DefaultWorkingDirectory)/${{ parameters.tfWorkingDirectory }}"
            commandOptions: "-write=false -diff -recursive"

        - task: charleszipp.azure-pipelines-tasks-terraform.azure-pipelines-tasks-terraform-cli.TerraformCLI@0
          displayName: "Terraform Init"
          inputs:
            command: init
            workingDirectory: "$(System.DefaultWorkingDirectory)/${{ parameters.tfWorkingDirectory }}"
            commandOptions: "-reconfigure"
            backendType: local

        - task: charleszipp.azure-pipelines-tasks-terraform.azure-pipelines-tasks-terraform-cli.TerraformCLI@0
          displayName: "Terraform validate"
          inputs:
            workingDirectory: "$(System.DefaultWorkingDirectory)/${{ parameters.tfWorkingDirectory }}"

        - task: charleszipp.azure-pipelines-tasks-terraform.azure-pipelines-tasks-terraform-cli.TerraformCLI@0
          displayName: "Terraform Plan"
          inputs:
            command: plan
            workingDirectory: "$(System.DefaultWorkingDirectory)/${{ parameters.tfWorkingDirectory }}"
            environmentServiceName: "${{ parameters.serviceConnectionName }}"
            runAzLogin: true
            commandOptions: '-input=false -out="$(Build.ArtifactStagingDirectory)/tfplan-${{ parameters.environment }}"'
            publishPlanResults: "tfplan-${{ parameters.environment }}"
        - task: PublishBuildArtifacts@1
          displayName: "Publish Artifact: tfplan"
          inputs:
            PathtoPublish: "$(Build.ArtifactStagingDirectory)"
            ArtifactName: tfplan-out
    - job: approveplan
      dependsOn: plan
      pool: server
      timeoutInMinutes: 30
      steps:
        - task: ManualValidation@0
          inputs:
            instructions: "Review Terraform plan"
            notifyUsers: ''
            onTimeout:  reject


- stage: tf_apply
  displayName:  "Terraform Apply"
  dependsOn: tf_plan
  condition: | 
    and(
      succeeded(), eq(variables.applyBranch, 'true')
      )
  jobs:
    - job: apply
      steps:
        - task: DownloadPipelineArtifact@2
          inputs:
            artifact: 'tfplan-out'
            path: $(System.DefaultWorkingDirectory)
  
        - task: charleszipp.azure-pipelines-tasks-terraform.azure-pipelines-tasks-terraform-installer.TerraformInstaller@0
          displayName: 'Use Terraform latest'
          inputs:
            terraformVersion: '${{ parameters.terraformVersion }}'
  
        - task: charleszipp.azure-pipelines-tasks-terraform.azure-pipelines-tasks-terraform-cli.TerraformCLI@0
          displayName: 'Terraform Init'
          inputs:
            command: init
            workingDirectory: '$(System.DefaultWorkingDirectory)/${{ parameters.tfWorkingDirectory }}'
            commandOptions: '-reconfigure'
            backendType: local

        - task: charleszipp.azure-pipelines-tasks-terraform.azure-pipelines-tasks-terraform-cli.TerraformCLI@0
          displayName: 'Terraform Apply'
          inputs:
            command: apply
            workingDirectory: '$(System.DefaultWorkingDirectory)/${{ parameters.tfWorkingDirectory }}'
            environmentServiceName: '${{ parameters.serviceConnectionName }}'
            runAzLogin: true
            commandOptions: '$(System.DefaultWorkingDirectory)/tfplan-${{ parameters.environment }}"'

- stage: setup_jumphost
  dependsOn: tf_apply
  displayName:  "Setting up Jumphost"
  jobs:
    - job: disable_host_key_checking
      displayName: "Disable hostkeychecking"
      dependsOn: startsetup
      steps:
      - task: Bash@3
        inputs:
          targetType: 'inline'
          script: 'ssh -o StrictHostKeyChecking=no $(cat servchal/infra/jumpserver01-private-ip)'
        continueOnError: true
    - job: create_pv_key_files
      dependsOn: startsetup
      variables:
      - group: servchal-keys
      steps:
        - script: |
           echo $JUMPKEY >> servchal/ansible/jump_serv_id_rsa
           chmod 0400 servchal/ansible/jump_serv_id_rsa
           echo $APPKEY >> servchal/ansible/app_serv_id_rsa
           chmod 0400 servchal/ansible/app_serv_id_rsa
    - job: populate_inventory
      dependsOn: startsetup
      steps:
        - script: |
           echo "[jumpservers]" >> servchal/ansible/inventory
           cat infra/jumpserver01-public-ip >> servchal/ansible/inventory
    - job: run_ansible_setup
      dependsOn:
       - disable_host_key_checking
       - create_pv_key_files
       - startsetup
      displayName: "Running ansible playbook to setup the jumphost"
      steps:
      - task: Bash@3
        inputs:
          targetType: 'inline'
          script: 'ansible-playbook setupjump.yml --extra-vars ansible_ssh_private_key_file=jump_serv_id_rsa --extra-vars ansible_user=azureuser'
          workingDirectory: 'servchal/ansible'

- stage: deploy_application
  displayName:  "Deploying Application"
  dependsOn: setup_jumphost
  condition: succeeded()
  jobs:
    - job: deploy_app
      steps:
        - script: |
           jumpip=`cat infra/jumpserver01-public-ip`
           #appserv1ip=`cat infra/appserver01-private-ip`
           #appserv2ip=`cat infra/appserver02-private-ip`
           #ssh -i ansible/jump_serv_id_rsa azureuser@"${jumpip}" echo $appserv1ip >> /home/azureuser/servchal/ansible/inventory
           #ssh -i ansible/jump_serv_id_rsa azureuser@"${jumpip}" echo $appserv2ip >> /home/azureuser/servchal/ansible/inventory
           ssh -i ansible/jump_serv_id_rsa azureuser@"${jumpip}" ansible-playbook /home/azureuser/servchal/ansible/playbook.yml --extra-vars ansible_ssh_private_key_file=/home/azureuser/servchal/ansible/app_serv_id_rsa --extra-vars ansible_user=azureuser
    - job: clean_up
      dependsOn: deploy_app
      steps:
        - script: |
           jumpip=`cat infra/jumpserver01-public-ip`
           ssh -i ansible/jump_serv_id_rs azureuser@"${jumpip}" rm -rf /home/azureuser/servchal