---
- name: Ansible script to configure the app servers and deploy the app as a service
  hosts:  all
  serial: 1
  tasks:
    - name: Disable SELinux in config file
      selinux:
        state: disabled

    - name: Disable SELinux in current session
      shell:
        cmd:  setenforce 0

    - name: Copy the script file
      copy:
        src:  /home/azureuser/servchal/ansible/files/runChallenge.sh
        dest: /opt/
        owner: root
        group: root
        mode: '0700'

    - name: Copy the service file
      copy:
        src: /home/azureuser/servchal/ansible/files/servchal.service
        dest: /etc/systemd/system
        owner: root
        group: root

    - name: Copy the application binary
      copy:
        src:  /home/azureuser/servchal/ansible/artefacts/TechChallengeApp
        dest: /opt
        owner: root
        group: root
        mode: '0700'

    - name: Copy the application config
      copy:
        src: /home/azureuser/servchal/ansible/artefacts/conf.toml
        dest: /opt


    - name: enable and start the service
      service:
        name: servchal
        state:  started
        enabled:  yes

    - name: Seed database
      shell:
        cmd:  /opt/TechChallengeApp updatedb
        chdir: /opt/

    - name: Copy the nginx installation file
      copy:
        src:  /home/azureuser/servchal/ansible/files/nginx-1.22.1-1.el8.ngx.x86_64.rpm
        dest: /tmp/nginx-1.22.1-1.el8.ngx.x86_64.rpm

    - name: Run the nginx installation
      shell:
        cmd:  rpm -ivh /tmp/nginx-1.22.1-1.el8.ngx.x86_64.rpm
      ignore_errors:  true

    - name: Copy the nginx config file
      copy:
        src:  /home/azureuser/servchal/ansible/files/default_nginx.conf
        dest: /etc/nginx/conf.d/default.conf
      notify: 
        - restart nginx

    - name: Add the firewall rule
      firewalld:
        port: 80/tcp
        permanent: yes
        state: enabled

      notify:
        - reload firewall


  handlers:
    - name: restart nginx
      service:  
        name: nginx
        state:  restarted
        enabled: yes
    - name: reload firewall
      service:  
        name: firewalld
        state:  restarted
        enabled: yes
    
