---
- name: Ansible script to setup the jump host
  hosts: jumphosts
  remote_user: azureuser
  vars:
    appserver_ips: 
    - "{{lookup('ansible.builtin.file', '../infra/appserver01-private-ip') }}"
    - "{{lookup('ansible.builtin.file', '../infra/appserver02-private-ip') }}"    
  tasks:
    - name: Set proper DNS
      lineinfile:
        path: /etc/resolv.conf
        regexp: '^nameserver'
        line: nameserver 168.63.129.16
    - name: Install Ansible
      apt:
        name: ansible
        state: present
        update_cache: yes
    - name: Clone the repo
      git:
        repo: 'https://github.com/ihsanizwer/servchal.git'
        dest: /home/azureuser/servchal
        update: no
      become: false
    - name: Copy the App Server private key to the jumpserver
      copy:
        src:  app_serv_id_rsa
        dest: /home/azureuser/servchal/app_serv_id_rsa
        mode: '0400'
      become: false
    - name: Populate the inventory with the appserver hosts
      lineinfile:
        path: /home/azureuser/servchal/ansible/inventory
        line: "{{ item  }}"
      with_items:  "{{ appserver_ips }}"
    - name: Disable stricthostkey checking for appservers as default user
      shell:
        cmd:  "ssh -o StrictHostKeyChecking=no {{ item }}"
      with_items: "{{ appserver_ips }}"
      ignore_errors: true
      become: false

    - name: Disable stricthostkey checking for appservers as super user
      shell:
        cmd:  "ssh -o StrictHostKeyChecking=no {{ item }}"
      with_items: "{{ appserver_ips }}"
      ignore_errors: true

    - name: Set up alias for runnning the playbook later
      shell:
        cmd: "chmod +x /home/azureuser/servchal/ansible/execute_play.sh && echo 'alias execplay=/home/azureuser/servchal/ansible/execute_play.sh' >> /home/azureuser/.bashrc"

